export type EffectType = BuffType | DebuffType | ItemSetPassive | ClassPasives;

export enum BuffType {
  CHARGE = 'CHARGE',
  FURY_POTION = 'FURY_POTION',
  ENERGY_POTION = 'ENERGY_POTION',
  ARMOR_POTION = 'ARMOR_POTION',
  SPEED_POTION = 'SPEED_POTION',
  PENETRATION_POTION = 'PENETRATION_POTION',
  CRIT_POTION = 'CRIT_POTION',
  DODGE_POTION = 'DODGE_POTION',
  BLOCK_POTION = 'BLOCK_POTION',
  ACCURACY_POTION = 'ACCURACY_POTION',
  SHIELD = 'SHIELD'
}

export enum DebuffType {
  POISONED = 'POISONED',
  BURNING = 'BURNING',
  BLEEDING = 'BLEEDING',
  WEAKENED = 'WEAKENED',
  SLOWED = 'SLOWED',
  VULNERABLE = 'VULNERABLE',
  ARMOR_BROKEN = 'ARMOR_BROKEN',
  BLINDED = 'BLINDED',
  STUNNED = 'STUNNED',
  CURSED = 'CURSED',
  CONFUSED = 'CONFUSED',
  DRAINED = 'DRAINED',
  EXHAUSTED = 'EXHAUSTED'
}

export enum ItemSetPassive {
  DIVINE_SPIRIT = 'DIVINE_SPIRIT',
  BLOOD_LUST = 'BLOOD_LUST',
  SERPENT_INFUSION = 'SERPENT_INFUSION',
  MELTING_BODY = 'MELTING_BODY',
  SHARP_BODY = 'SHARP_BODY',
  ILLUSIONARY_DANCE = 'ILLUSIONARY_DANCE',
  ABYSSAL_SURGE = 'ABYSSAL_SURGE',
  RADIANT_BARRIER = 'RADIANT_BARRIER',
  FLAMING_ECHO = 'FLAMING_ECHO',
  THUNDER_GODS_WRATH = 'THUNDER_GODS_WRATH',
  FROZEN_GRAVE = 'FROZEN_GRAVE',
  PRIMAL_HUNGER = 'PRIMAL_HUNGER',
  VENOM_BLOOM = 'VENOM_BLOOM',
  MENTAL_COLLAPSE = 'MENTAL_COLLAPSE',
  DROWNING_PULSE = 'DROWNING_PULSE',
}

export enum ClassPasives {
  BERSEKER_RAGE = 'BERSEKER_RAGE',
  ARCANE_MASTERY = 'ARCANE_MASTERY',
  BACKSTAB = 'BACKSTAB',
  SOUL_REAPER = 'SOUL_REAPER',
}
