export enum BuffType {
  CHARGE = 'CHARGE',
  FURY_POTION = 'FURY_POTION',
  ENERGY_POTION = 'ENERGY_POTION',
  ARMOR_POTION = 'ARMOR_POTION',
  SPEED_POTION = 'SPEED_POTION',
  PENETRATION_POTION = 'PENETRATION_POTION',
  CRIT_POTION = 'CRIT_POTION',
  DODGE_POTION = 'DODGE_POTION',
  BLOCK_POTION = 'BLOCK_POTION',
  ACCURACY_POTION = 'ACCURACY_POTION',
}

export enum DebuffType {
  POISONED = 'POISONED',
  BURNING = 'BURNING',
  BLEEDING = 'BLEEDING',
  WEAKENED = 'WEAKENED',
  SLOWED = 'SLOWED',
  VULNERABLE = 'VULNERABLE',
  ARMOR_BROKEN = 'ARMOR_BROKEN',
  BLINDED = 'BLINDED',
  STUNNED = 'STUNNED',
}

export enum ItemSetPassive {
  // SETS
  // HAND_OF_GOD
  DIVINE_SPIRIT = 'DIVINE_SPIRIT',
  // VAMPIRIC_BLOODLINES
  BLOOD_LUST = 'BLOOD_LUST',
  // DEATH_RITUALS
  SERPENT_INFUSION = 'SERPENT_INFUSION',
  // BURNING_DESIRE
  MELTING_BODY = 'MELTING_BODY',
  // IRON_MAIDEN
  SHARP_BODY = 'SHARP_BODY',
  // SHADOW_DANCER
  ILLUSIONARY_DANCE = 'ILLUSIONARY_DANCE',
}


export enum ClassPasives {
  BERSEKER_RAGE = 'BERSEKER_RAGE',
  ARCANE_MASTERY = 'ARCANE_MASTERY',
  BACKSTAB = 'BACKSTAB',
  SOUL_REAPER = 'SOUL_REAPER'
}



export type EffectType = BuffType | DebuffType | ItemSetPassive | ClassPasives;
